#	Copyright (C)    horbyn, 2020
#             (hoRbyn4zZ@outlook.com)
#
# The procedure of writing kernel to disk are as follow:
# 1. Both all .bin are generated first than writed into disk
# 2. The .bin of the boot is generated individually first
# 3. The kernel is generated by ld command with head.o linking first
# 4. Using objcopy command to gain pure .bin after linking by ld command
#
# The function of head are as follow:
# 1. Move the whole kernel from 0x10000 to 0
# 2. Enable Protect Mode
# 3. Jump into the real kernel

	.text
	.globl start
	.code16

	## function 1.
	cld
	movw $0x1000, %ax
	movw %ax,     %ds
	movw $0,      %ax
	movw %ax,     %es
	xorw %si,     %si
	xorw %di,     %di
	movw $512>>1, %cx
	rep  movsl

	jmp  .
